services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: divine_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0LVDUToUxZMoKPNUk4tbD5VC
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d divine_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  minio:
    image: minio/minio:RELEASE.2025-01-20T14-49-07Z-cpuv1
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: Ime3T7KXUVk3z1LbovD0iFbF
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 20

  divine-back:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3005
      DATABASE_URL: postgresql://postgres:0LVDUToUxZMoKPNUk4tbD5VC@postgres:5432/divine_db?schema=public
      JWT_SECRET: 073964fe58f4a2a72ff8413f63538211d50368a02dbc500a20f148743a6bf575
      JWT_REFRESH_SECRET: 21fd45c64711631c51d54e16bca98fe0e29e76a79bab443f0ec382fbf989c3f1
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: Ime3T7KXUVk3z1LbovD0iFbF
      MINIO_BUCKET_NAME: divine-shop
      PRISMA_SYNC: dbpush
      OTP_TRACE: "true"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    extra_hosts:
      - "api.sms.ir:185.211.56.44"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports:
      - "3005:3005"

volumes:
  postgres_data:
  minio_data:
